### ISSUE TITLE
Non functional

### ISSUE THREAD

**Issue by antiartist** [corydeppen/Producteev-Chrome#2]
Installed the extension and does not work at all.  Clicking on the chrome icon does nothing (see first image).  The "options" selection is unavailable (see second image.  ) Judging from the reviews on the Chrome webstore, this extension hasn't worked since 2011.  If the extension is no longer supported, please take it down from the webstore.  Thanks

![image](https://cloud.githubusercontent.com/assets/5401674/7968702/8b46e766-09ef-11e5-9a09-b335d2f23b84.png)

![image](https://cloud.githubusercontent.com/assets/5401674/7968722/a5e25560-09ef-11e5-98f0-cbf04dbb17b7.png)

**Comment by corydeppen** [comment]
The extension has been unpublished.
